name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: '24'

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'

    - name: Check npm version
      shell: bash
      run: npm --version

    - name: Update npm
      shell: bash
      run: npm install -g npm@latest

    # NPM v11.5.0 added support for OIDC publish
    # https://docs.npmjs.com/cli/v11/using-npm/changelog#1150-2025-07-24
    - name: Check npm version
      shell: bash
      run: npm --version

    - name: Install
      run: pnpm install
      shell: bash
