import plugin from 'eslint-plugin-unicorn'
import { test } from 'vitest'

import { checkRules } from './test-utils.js'
import { unicornRules } from './unicorn.js'

test('Unicorn rules should match recommended rules', () => {
  checkRules({
    plugin,
    currentRules: unicornRules,
    recommendedRules: plugin.configs.recommended.rules || {},
    disabledRules: [
      // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v62.0.0/docs/rules/catch-error-name.md
      'unicorn/catch-error-name',

      // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v62.0.0/docs/rules/consistent-assert.md
      'unicorn/consistent-assert',

      'unicorn/consistent-date-clone',
      'unicorn/consistent-empty-array-spread',
      'unicorn/consistent-existence-index-check',
      'unicorn/consistent-function-scoping',
      'unicorn/empty-brace-spaces',
      'unicorn/expiring-todo-comments',
      'unicorn/filename-case',
      'unicorn/import-style',
      'unicorn/new-for-builtins',
      'unicorn/no-anonymous-default-export',
      'unicorn/no-array-callback-reference',
      'unicorn/no-array-for-each',
      'unicorn/no-array-method-this-argument',
      'unicorn/no-array-reduce',
      'unicorn/no-array-reverse',
      'unicorn/no-array-sort',
      'unicorn/no-await-expression-member',
      'unicorn/no-await-in-promise-methods',
      'unicorn/no-console-spaces',
      'unicorn/no-document-cookie',
      'unicorn/no-empty-file',
      'unicorn/no-immediate-mutation',
      'unicorn/no-invalid-fetch-options',
      'unicorn/no-lonely-if',
      'unicorn/no-magic-array-flat-depth',
      'unicorn/no-negated-condition',
      'unicorn/no-nested-ternary',
      'unicorn/no-new-array',
      'unicorn/no-null',
      'unicorn/no-object-as-default-parameter',
      'unicorn/no-process-exit',
      'unicorn/no-single-promise-in-promise-methods',
      'unicorn/no-static-only-class',
      'unicorn/no-thenable',
      'unicorn/no-this-assignment',
      'unicorn/no-typeof-undefined',
      'unicorn/no-unnecessary-array-flat-depth',
      'unicorn/no-unnecessary-array-splice-count',
      'unicorn/no-unnecessary-await',
      'unicorn/no-unnecessary-polyfills',
      'unicorn/no-unnecessary-slice-end',
      'unicorn/no-unreadable-array-destructuring',
      'unicorn/no-unreadable-iife',
      'unicorn/no-useless-collection-argument',
      'unicorn/no-useless-error-capture-stack-trace',
      'unicorn/no-useless-fallback-in-spread',
      'unicorn/no-useless-length-check',
      'unicorn/no-useless-promise-resolve-reject',
      'unicorn/no-useless-switch-case',
      'unicorn/no-useless-undefined',
      'unicorn/no-zero-fractions',
      'unicorn/numeric-separators-style',
      'unicorn/prefer-at',
      'unicorn/prefer-blob-reading-methods',
      'unicorn/prefer-class-fields',
      'unicorn/prefer-classlist-toggle',
      'unicorn/prefer-code-point',
      'unicorn/prefer-date-now',
      'unicorn/prefer-default-parameters',
      'unicorn/prefer-dom-node-append',
      'unicorn/prefer-dom-node-dataset',
      'unicorn/prefer-dom-node-remove',
      'unicorn/prefer-dom-node-text-content',
      'unicorn/prefer-event-target',
      'unicorn/prefer-global-this',
      'unicorn/prefer-logical-operator-over-ternary',
      'unicorn/prefer-math-min-max',
      'unicorn/prefer-modern-dom-apis',
      'unicorn/prefer-modern-math-apis',
      'unicorn/prefer-module',
      'unicorn/prefer-native-coercion-functions',
      'unicorn/prefer-object-from-entries',
      'unicorn/prefer-optional-catch-binding',
      'unicorn/prefer-prototype-methods',
      'unicorn/prefer-query-selector',
      'unicorn/prefer-reflect-apply',
      'unicorn/prefer-response-static-json',
      'unicorn/prefer-set-has',
      'unicorn/prefer-set-size',
      'unicorn/prefer-spread',
      'unicorn/prefer-string-replace-all',
      'unicorn/prefer-string-slice',
      'unicorn/prefer-string-trim-start-end',
      'unicorn/prefer-switch',
      'unicorn/prefer-ternary',
      'unicorn/prefer-top-level-await',
      'unicorn/prevent-abbreviations',
      'unicorn/relative-url-style',
      'unicorn/require-array-join-separator',
      'unicorn/require-module-attributes',
      'unicorn/require-module-specifiers',
      'unicorn/require-number-to-fixed-digits-argument',
      'unicorn/switch-case-braces',
      'unicorn/template-indent',
      'unicorn/text-encoding-identifier-case',
    ],
    enabledRules: [
      // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v62.0.0/docs/rules/better-regex.md
      'unicorn/better-regex',

      // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v62.0.0/docs/rules/prefer-import-meta-properties.md
      'unicorn/prefer-import-meta-properties',
    ],
  })
})
