name: Release

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          command: manifest

      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Publish to NPM
        run: pnpm -r publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
